# Generated by Django 2.2.10 on 2021-12-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'custom polls',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('text question', 'text question'), ('one variant choice', 'one variant choice'), ('plural variants choice', 'plural variants choice  ')], default='text question', max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_polls.Poll')),
            ],
            options={
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='RespondentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('custom_poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_polls.CustomPoll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_polls.Question')),
            ],
            options={
                'verbose_name_plural': "respondets' answers",
            },
        ),
        migrations.AddField(
            model_name='custompoll',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_polls.Poll'),
        ),
    ]
